### ISSUE TITLE
Goal of this project?

### ISSUE THREAD

**Issue by stevelorenz** [williamofockham/nb2#1]
Dear nb2 developer,
I am a PhD student working in NFV related topics and have learned a lot for practical container setups from wiliamofockham project. Thanks so much for your great effort.
May I ask about the goal of this project (nb2)? Currently, I develop DPDK applications in pure C and wants to use a safer and higher level language like Rust. The NetBricks's code base is big for Rust beginners like me. Is this project aiming at providing lean and easy-to-use Rust bindings for DPDK?

Thanks so much for your help.

**Comment by drunkirishcoder** [comment]
Hi @stevelorenz, glad you found our project helpful. For now `nb2` is an experiment. We are trying to see if we can remove the C code that glues NetBricks to DPDK through using FFI bindings directly. Our goal is still to provide a higher abstraction for NFV development. We've rewritten how packets are parsed through our typed packet work. Next we'd like to improve the framework to make it easier to extend with more DPDK features.

p.s. If you are looking for a pure one-to-one DPDK to rust binding, there's [this project](https://github.com/flier/rust-dpdk), which I certainly took some inspiration from.

**Comment by stevelorenz** [comment]
Hi @drunkirishcoder , thanks so much for your helpful response.
The higher abstraction is great for developers to make "VNF development black magic" easier :smile: . 
Thanks for your effort and I will try and keep watching this framework.
